name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install webpack dependencies
        run: |
          cd wp-content/themes/rosengarten
          npm install
      - name: Build js and scss
        run: |
          cd wp-content/themes/rosengarten
          npm run build:production

      - name: Add deploy_key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "$DEPLOY_KEY" > "$HOME/deploy_key"
          chmod 600 "$HOME/deploy_key"
      - name: rsync files
        run: |
          rsync -avhz -e "ssh -o StrictHostKeyChecking=no -i $HOME/deploy_key" --exclude-from 'rsync-exclude-list.txt' . tom@93.90.202.66:/var/www/html/wordpress
  test:
    runs-on: ubuntu-latest
    needs: deploy

    services:
      hub:
        image: selenium/hub:3.141.59-gold
        ports:
          - 4444:4444
      chrome:
        image: selenium/node-chrome:3.141.59-20200409
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - uses: actions/checkout@v2

      - name: Install Webdriver
        run: |
          npm install @actions/core selenium-webdriver

      - name: Run test
        run: |
          cd tests
          SELENIUM_REMOTE_URL="http://localhost:4444/wd/hub" node test.js
